//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auctionfinal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        public int playerid { get; set; }
        public string playername { get; set; }
        public Nullable<int> baseprice { get; set; }
        public byte[] photo { get; set; }
    }
}
